site_name: Sheeep's Zone
site_url: https://qiqiqihy.github.io/Sheeep-Zone/

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest

nav:
  - Home: index.md
  - SLAM Basics:
      - SIFT: SLAM-Basics-SIFT.md
      - GFTT: SLAM-Basics-GFTT.md
      - SURF: SLAM-Basics-SURF.md

markdown_extensions:
  - footnotes
